### ISSUE TITLE
Can't find "eeg_data" function

### ISSUE THREAD

**Issue by antonietamg** [craddm/eegUtils#131]
Hello. Some months ago I wrote my scripts to downsample and plot some recordings and I applyed the eeg_data() function without problems. Now I can't run my script because R says that the eeg_data() function doesn't exists. 

I checked the functions in the package and yes, the eeg_data() function is not there anymore. The function was eliminated in the last upgrade or maybe I'm doing something wrong?

**Comment by craddm** [comment]
Hi, I don't know when the `eeg_data()` function would have been callable for you as a user - it's an internal function that has never been intended for use by users. The only way you could use it is by using it as `eegUtils:::eeg_data()`, or if you were using the package as a collection of scripts and had sourced `class_handling.R` rather than installing the whole thing as a library. So I'm not sure how you were using it in your scripts...
