### ISSUE TITLE
Installation Attempt Failure

### ISSUE THREAD

**Issue by bgrawls** [craddm/eegUtils#134]
I've tried to install the package (and the development package) in R4.2.2 w/ rstudio via remotes::install_github(), devtools::install_github(), and githubinstall::gh_install_packages(), with dependencies set to both TRUE and FALSE.  All three have resulted in the following:

Warning message:
In i.p(...) :
  installation of package ‘/var/folders/n9/pmj1bhf538zghtnbd4rzvgt00000gn/T//Rtmp0OTT8a/file74111b8c40e0/eegUtils_0.7.0.9000.tar.gz’ had non-zero exit status

Working off of an m1 macbook pro running Ventura 13.2.1.

**Comment by craddm** [comment]
Going to need a little more info - it compiles fine on my M1 Macbook Pro (albeit still on Monterey) so I can't replicate your problem locally. Is your compilation toolchain all set up? (been a while since I did it...)

May also want to try a precompiled version from R-Universe - https://craddm.r-universe.dev/eegUtils

**Comment by craddm** [comment]
Closed as no further information supplied and cannot replicate
