### ISSUE TITLE
Other montages

### ISSUE THREAD

**Issue by themeo** [craddm/eegUtils#50]
I work in a lab that has custom caps and electrode locations. Is it possible to define/enter custom electrode locations so that topoplot() can display maps properly?

**Comment by craddm** [comment]
Should certainly be doable - do you have a file with locations? If so, what format is it in? It's possible to pass custom locations using the chanLocs parameter for topoplot, but I haven't used that for a while; the input for that should be a data.frame with columns electrode, x and y, I think. 

The normal channel info for an eegUtils objects has the structure shown here:
[https://craddm.github.io/eegUtils/reference/channels.html](https://craddm.github.io/eegUtils/reference/channels.html)

**Comment by themeo** [comment]
This is great! (I somehow missed the chanLocs argument of topoplot()). How
do I obtain the x and y values (I assume they are x and y on the plot?). I
have my coordinates both in the polar and cartesian coordinate systems.

**Comment by craddm** [comment]
If you have cartesian xyz coordinates, taking just the xy coordinates from those should give you an orthographic projection; otherwise you can try doing a stereographic projection from the polar coordinates:
https://www.mattcraddock.com/blog/2017/02/25/erp-visualization-creating-topographical-scalp-maps-part-1/

There's some internal functions that might do that job too, but I think you'd have to call a chain of them, so might be better to avoid...
