### ISSUE TITLE
Installation issue (macOS Catalina problem?)

### ISSUE THREAD

**Issue by langestroop** [craddm/eegUtils#52]
Hi, 

I've just tried to install eegUtils via RStudio (R version 3.6.1) and I got this error:

Error: Failed to install 'eegUtils' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES'

I suspect it might be related to the fact that I'm currently using macOS Catalina, since I didn't encounter any error in the past when using eegUtils. What do you think?

Many thanks for your time.
Alberto

**Comment by craddm** [comment]
Hi, 

I'm really not sure about that one! I don't think it's a problem at our end. Makes me wonder if if there was some internet access issue/outage, since it says it can't open the URL. I'd note also that although you're on Catalina, the URL says El Capitan... also it could be that one of the dependencies isn't available on CRAN as a binary for some reason (but they all seem to be there to me when i follow the URL...)

The packages builds fine on Travis with macOS High Sierra

Here's a link where someone had a similar problems:
https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578

Cheers,
Matt

**Comment by craddm** [comment]
closing as no further reports
